version: "3.9"
services:
  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: 
          - node.role == worker
    volumes: 
      - redis_data:/data
    ports:
      - "6379:6379" # this is default port even if not mentioned port
    #command: redis-server /usr/local/etc/redis/redis.conf
  web:
    image: stackdemo:v1
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  redis_data:
    name: docker-compose-redis-volume
    driver: local