version: "3.9"
services:
  redis:
    image: "redis:alpine"
    container_name: customs-dev-redis
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: 
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints: 
          - node.role == worker
    volumes: 
      - redis_data:/data
    ports:
      - "6000:6000" # this is default port even if not mentioned port
    #command: redis-server /usr/local/etc/redis/redis.conf
  web:
    image: 127.0.0.1:5000/stackdemo
    hostname: '{{.Node.Hostname}}'
    build: .
    ports:
      - "8000:8000"
    deploy:
      mode: replicated    
      replicas: 1
      restart_policy: 
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    depends_on:
      - redis
  visualizer:
      image: dockersamples/visualizer
      ports:
        - "8080:8080"
      stop_grace_period: 1m30s
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]
volumes:
  redis_data:
    name: docker-compose-redis-volume
    driver: local