version: "3.9"
services:
  redis:
    image: "redis:alpine"
    volumes: 
      - redis_data:/data
    ports:
      - "6379:6379" # this is default port even if not mentioned port
    command: redis-server /usr/local/etc/redis/redis.conf
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  redis_data:
    name: docker-compose-redis-volume
    driver: local